name: CI

on:
  push:
    # you might need to change main to master
    branches: [main]
  pull_request:
    # you might need to change main to master
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
        name: yarn install

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: eslint './src/**/*.{ts,tsx}' --ext .tsx

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: prettier --config .prettierrc './src/**/*.{ts,tsx}' --write
      
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: tsc

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build